### ISSUE TITLE
PR for cache hit/miss breaks ngxtop

### ISSUE THREAD

**Issue by oxr463** [ngxtop/ngxtop#6]
```sh
running for 18 seconds, 0 records processed: 0.00 req/sec

Summary:
|   count | avg_bytes_sent   |   2xx |   3xx |   4xx |   5xx |   cached |   non cached |
|---------+------------------+-------+-------+-------+-------+----------+--------------|
|       0 |                  |     0 |     0 |     0 |     0 |        0 |            0 |

Detailed:
| request_path   | count   | avg_bytes_sent   | 2xx   | 3xx   | 4xx   | 5xx   | cached   | non cached   |
|----------------+---------+------------------+-------+-------+-------+-------+----------+--------------|


```

It simply never updates.

See: https://github.com/ngxtop/ngxtop/releases/tag/0.0.3-alpha.3

**Comment by oxr463** [comment]
Workaround is to downgrade ngxtop to version 0.0.3-alpha.1,

```sh
pip3 install --upgrade ngxtop-ce==0.0.3a1
```

**Comment by Narrat** [comment]
And sadly this PR is a mess with commits all over the place and severly non-working if partially applied, which makes bisecting the changes kinda ugly.
Squashed the commits from the PR and removed partially unimportant changes. Maybe it will help you with debugging. At first glance I cannot see an obvious culprit.
https://github.com/Narrat/ngxtop/commit/272a17f7aad85e858e5f6bd0aeba47f9141db275

**Comment by oxr463** [comment]
@neverrend, any ideas?

**Comment by oxr463** [comment]
See: https://github.com/ngxtop/ngxtop/compare/0.0.3-alpha.1...0.0.3-alpha.5

**Comment by oxr463** [comment]
Yanked `0.0.3a6` from PyPI.
